### PR TITLE
added no bg and border button

### PR DESCRIPTION
**Pull request by JefMari**
[https://github.com/dev-onenetworkecommerce/aia/issues/77]
[https://github.com/dev-onenetworkecommerce/aia/issues/78]
capture
when buttons are hovered
capture2

### CODE REVIEW

**Comment by JefMari** [comment]
@srph

**Comment by srph** [comment]
Name it `-plain` instead of `-clear`.

**Comment by srph** [comment]
Also, you might be referring to https://github.com/dev-onenetworkecommerce/aia/issues/78 not https://github.com/dev-onenetworkecommerce/aia/issues/77

**Comment by srph** [comment]
Oops, my bad. I think I misunderstood the context.

This should be `.-link` (just like TWBS's `btn-link`).

**Comment by JefMari** [comment]
[https://github.com/dev-onenetworkecommerce/aia/issues/80]
capture1

**Comment by srph** [comment]
THANKS :star:

**Pull request merged**
