### PR TITLE
[WIP] Init loaders.

### PR DESCRIPTION
**Pull request by srph**
screen shot 2015-09-26 at 8 47 21 pm

**Work in progress; do not merge.**
- [x] Basic Loader
- [ ] Work with buttons
- [ ] Work with slate
- [ ] Approval from designers

Closes https://github.com/dev-onenetworkecommerce/aia/issues/33

### CODE REVIEW

**Comment by brianbodollo** [comment]
loader on button
image

**Comment by brianbodollo** [comment]
loader on slate
image

**Comment by brianbodollo** [comment]
@srph

**Comment by srph** [comment]
Put the loader above, just like the icons. Icons and loaders should always be placed on top in slates.

**Comment by brianbodollo** [comment]
image

**Comment by srph** [comment]
where's the margin? lol. thanks. anyway, i'll also wait for the buttons. lastly, ask the designers if it looks good.

We haven't received any loader design. But if they have any, discuss it to the team (us). Animated SVGs would be awesome.

\* Don't forget to fix merge conflicts. This was submitted month ago (lol).

**Comment by brianbodollo** [comment]
image

**Comment by brianbodollo** [comment]
image

**Comment by srph** [comment]
- Like icons, spacers should have a `margin-bottom` by default in Slate.
- We need a light-colored loader.

**Pull request merged**
