### PR TITLE
Button line height

### PR DESCRIPTION
**Pull request by brianbodollo**
https://github.com/dev-onenetworkecommerce/aia/issues/76

### CODE REVIEW

**Comment by brianbodollo** [comment]
image

**Comment by srph** [comment]
- `line-height` is supposed to be the same as the `height`.

https://github.com/dev-onenetworkecommerce/aia/issues/76#issue-111744463:

> This is due to the line-height. Just need to be set to the same value of height.
- Also, you can edit your comment instead of posting another comment..

**Comment by brianbodollo** [comment]
i tried but not all are applicable.

**Comment by srph** [comment]
Mind elaborating?

**Comment by brianbodollo** [comment]
example if `-small`'s height is 30px and line-height of 20px the result looks like this
image

but when the `-small`'s height is 30px and line-height of 30px the result looks like this
image

**Comment by srph** [comment]
That's because `-small` has a vertical padding which needs to be removed. Check https://github.com/dev-onenetworkecommerce/aia/pull/86/files#diff-31ce929838c3cc5ce8e73497309e9e18R82

**Comment by brianbodollo** [comment]
thanks, done.

**Pull request merged**
