### PR TITLE
remove border bottom if tr is last child of table on panel

### PR DESCRIPTION
**Pull request by brianbodollo**
https://github.com/dev-onenetworkecommerce/aia/issues/181

### CODE REVIEW

**Comment by srph** [comment]
You're only supposed to remove the `border-bottom` for a table in a panel, not for the a raw/standalone table.

**Comment by maebe22** [comment]
[]

**Comment by brianbodollo** [comment]
it is the table inside the panel not the raw one.

**Comment by srph** [comment]
What's [this](https://github.com/dev-onenetworkecommerce/aia/pull/186/files#diff-41b3dd6f9f68e4803c4fdc9c9e0258c9R42) then?

**Comment by srph** [comment]
Oh, I see. Nevermind. Just merge :+1:

**Pull request merged**
