### PR TITLE
Add example for button with icon inside

### PR DESCRIPTION
**Pull request by JefMari**
For issue [https://github.com/dev-onenetworkecommerce/aia/issues/81]
capture

### CODE REVIEW

**Comment by JefMari** [comment]
Should i remove the `default` button in the sizes?

**Comment by srph** [comment]
Screenshot plox

> Should i remove the default button in the sizes?

What do you mean?

**Comment by JefMari** [comment]
becuase it is already in the variant and `default` is not categorize as measure of size. IMO

**Comment by srph** [comment]
Nah, t's good.

**Pull request merged**
