### PR TITLE
fix addon

### PR DESCRIPTION
**Pull request by JefMari**
for issue #146 
image

### CODE REVIEW

**Comment by brianbodollo** [comment]
i think the borders are too dimmed and not applicable with the design tho, lets confirm to @srph about this.

**Comment by JefMari** [comment]
He already confirm it, see #150

**Comment by srph** [comment]
I'll consider this if the designers accept this, probably after our sit-down.

**Comment by JefMari** [comment]
:+1:

**Comment by JefMari** [comment]
Will also done by #191 , close this now

**Pull request closed without merging**
