### PR TITLE
added -active class for future use when button is pressed

### PR DESCRIPTION
**Pull request by brianbodollo**

### CODE REVIEW

**Comment by srph** [comment]
- Provide screenshots please.

I still can't merge this as the design will be undergoing changes.
- Inverted (bordered) buttons will have a background when hovered instead of being darkened.
- Normal buttons will be lightened when hovered instead of being darkened.

**Comment by brianbodollo** [comment]
wala na atang sense to, delete ko nalang

**Comment by srph** [comment]
Huh?

**Comment by srph** [comment]
> I still can't merge this as the design will be undergoing changes.

Not sure why you closed this.

**Pull request closed without merging**
