### PR TITLE
changed style of selected item on list-group

### PR DESCRIPTION
**Pull request by brianbodollo**
make the background blue if active

list-selected

### CODE REVIEW

**Comment by srph** [comment]
- I think we need to increase the the link height as indicated in the design.
- Also, normal links should be `$brand-black`.

**Comment by brianbodollo** [comment]
list-selected

@srph

**Comment by srph** [comment]
> Also, normal links should be $brand-black.

**Comment by maebe22** [comment]
list-selected

**Comment by brianbodollo** [comment]
should the borders become `$brand-gray-lt`

**Comment by srph** [comment]
Oh yeah, lastly, outer border should also be `$brand-gray-lt`.

**Comment by brianbodollo** [comment]
i've make it 2px because 1px is thin, really really thin which is not the same as the design

**Comment by srph** [comment]
Okay :ok_hand:. Send a screenshot.

**Comment by brianbodollo** [comment]
list-selected

**Comment by srph** [comment]
I think there's a visual malfunction because of its positioning. Can you try `1px`? `2px` is too much. If `1.5px` works, then I think let's go for that one.

**Comment by brianbodollo** [comment]
done!

**Comment by srph** [comment]
Screenshots?

**Comment by brianbodollo** [comment]
waits

**Comment by brianbodollo** [comment]
list-selected

**Pull request merged**
